databases:
  - name: ferver_db
    databaseName: ferver
    user: ferver_user

services:
  - type: web
    name: ferver-brasil
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input"
    startCommand: "python manage.py migrate && gunicorn app.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "True"
      - key: DATABASE_URL
        fromDatabase:
          name: ferver_db
          property: connectionString
      - key: MERCADOPAGO_ACCESS_TOKEN
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false