# Generated by Django 6.0.3 on 2026-03-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='ativo',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
