# Generated by Django 6.0.3 on 2026-03-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferver', '0004_cidade_estado_alter_perfil_cidade_cidade_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='mercadopago_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
