# Generated by Django 6.0.3 on 2026-03-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferver', '0005_perfil_mercadopago_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='perfis/'),
        ),
    ]