# Generated by Django 6.0.3 on 2026-03-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferver', '0006_perfil_foto2'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='top_geral',
            field=models.BooleanField(default=False, verbose_name='Top Geral (Banner)'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='boost',
            field=models.BooleanField(default=False, verbose_name='Destaque (Card)'),
        ),
    ]
