# Generated by Django 6.0.3 on 2026-03-09 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferver', '0007_perfil_top_geral_alter_perfil_boost'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='premium',
            field=models.BooleanField(default=False, verbose_name='Premium (7 fotos)'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='validade_destaque',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Validade Destaque'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='validade_premium',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Validade Premium'),
        ),
        migrations.CreateModel(
            name='FotoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='perfis/galeria/')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_adicionais', to='ferver.perfil')),
            ],
        ),
    ]
